image: cypress/browsers:node16.13.0-chrome95-ff94

test:
  script:
    - npm ci
    - npm run eslint
    - npm run lint:styles:report
    - npm run test
  stage: test
  cache:
    paths:
      - dist
      - coverage-jest

e2e-tests:
  variables:
    # BACKEND_TAG: '(if [ "$${CI_COMMIT_TAG}" == "" ]; then echo "1.3.5.$$CI_PIPELINE_IID"; else echo "$${CI_COMMIT_TAG}"; fi);'
    BACKEND_TAG: "latest"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_DB: "dash_test"
    POSTGRES_URL: "jdbc:postgresql://localhost:5432/dash_test"
  services:
    - name: postgres:13.2-alpine
    - name: arnaudf93:dash-webservices:"$BACKEND_TAG"
  script:
    - |-
      npm ci
      npm run test:e2e
  stage: test
  cache:
    paths:
      - cypress

generate-e2e-test-report:
  needs:
    - test
  script:
    - mkdir cypress/screenshots || true
    - npm run report:merge
    - npm run report:generate
    - npm run report:copyScreenshots
  artifacts:
    paths:
      - cypress/reports/html
  cache:
    policy: pull
    paths:
      - cypress

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build -- --base-href=https://afcompany.gitlab.io/CashManager-Web/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

coverage-report:
  stage: .post
  script:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -t ${CODECOV_TOKEN} -F coverage-jest
  cache:
    policy: pull
    paths:
      - coverage-jest

snyk-report:
  stage: .post
  script:
    - npm i -g snyk-to-html
    - npx snyk auth ${SNYK_TOKEN}
    - npx snyk test --json-file-output=snyk-report.json || true
    - npx snyk-to-html -i snyk-report.json -o snyk-report.html
  artifacts:
    expire_in: 30 days
    paths:
      - snyk-report.html
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: .post
  script:
    - sonar-scanner
  cache:
    policy: pull
    paths:
      - coverage-jest
