image: cypress/browsers:node16.13.0-chrome95-ff94

test:
  script:
    - npm ci
    - npm run eslint
    - npm run lint:styles:report
    - npm run test
    - npm run test:e2e
  stage: test
  cache:
    paths:
      - dist
      - cypress
      - coverage-jest

e2e-tests:
  script:
    - |-
      echo $CI_COMMIT_BRANCH
      docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
      docker pull postgres:13.2-alpine
      docker run -p 5432:5432 -d -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=dash_test postgres:13.2-alpine
      if [[ "$(git ls-remote --heads https://github.com/ArnaudFlaesch/Dash-WebServices $CI_COMMIT_BRANCH | wc -l)" == 1 && $CI_COMMIT_BRANCH != 'main' && $CI_COMMIT_BRANCH != 'main' ]]; then
        docker pull arnaudf93/dashwebservices:$CI_COMMIT_BRANCH
        docker run -p 8080:8080 -d --network="host" -e POSTGRES_URL=jdbc:postgresql://localhost:5432/dash_test -e OPENWEATHERMAP_KEY=${OPENWEATHERMAP_KEY} -e STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID} -e STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET} -e STEAM_USER_ID=${STEAM_USER_ID} -e STEAM_API_KEY=${STEAM_API_KEY} arnaudf93/dashwebservices:${GITHUB_REF#refs/*/}
      else
        docker pull arnaudf93/dashwebservices:latest
        docker run -p 8080:8080 -d --network="host" -e POSTGRES_URL=jdbc:postgresql://localhost:5432/dash_test -e OPENWEATHERMAP_KEY=${OPENWEATHERMAP_KEY} -e STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID} -e STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET} -e STEAM_USER_ID=${STEAM_USER_ID} -e STEAM_API_KEY=${STEAM_API_KEY} arnaudf93/dashwebservices:latest
      fi

generate-e2e-test-report:
  needs:
    - test
  script:
    - mkdir cypress/screenshots || true
    - npm run report:merge
    - npm run report:generate
    - npm run report:copyScreenshots
  artifacts:
    paths:
      - cypress/reports/html
  cache:
    policy: pull
    paths:
      - cypress

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build -- --base-href=https://afcompany.gitlab.io/CashManager-Web/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

coverage-report:
  stage: .post
  script:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -t ${CODECOV_TOKEN} -F coverage-jest
  cache:
    policy: pull
    paths:
      - coverage-jest

snyk-report:
  stage: .post
  script:
    - npm i -g snyk-to-html
    - npx snyk auth ${SNYK_TOKEN}
    - npx snyk test --json-file-output=snyk-report.json || true
    - npx snyk-to-html -i snyk-report.json -o snyk-report.html
  artifacts:
    expire_in: 30 days
    paths:
      - snyk-report.html
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: .post
  script:
    - sonar-scanner
  cache:
    policy: pull
    paths:
      - coverage-jest
