sonar.projectKey=ArnaudFlaesch_CashManager
sonar.organization=arnaudflaesch

sonar.projectName=CashManager
sonar.projectVersion=1.0

sonar.sources=src/app
sonar.sourceEncoding=UTF-8

sonar.exclusions=dist/**,nodes_modules/**
sonar.coverage.exclusions = "cypress/**", "/**/*.spec.ts"

sonar.css.stylelint.reportPaths=styleLintReport.json
